/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AlignmentIn,
  FetchIn,
  HTTPValidationError,
  PlaceOut,
  SearchPlacesParams,
  SurroundingsOut
} from '../../model';

import { httpClient } from '../../http-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Swiss addresses and parcels matching the text (geo.admin.ch), in LV95.
 * @summary Search Places
 */
export const getSearchPlacesUrl = (params: SearchPlacesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/geo/search?${stringifiedParams}` : `/api/v1/geo/search`
}

export const searchPlaces = async (params: SearchPlacesParams, options?: RequestInit): Promise<PlaceOut[]> => {
  
  return httpClient<PlaceOut[]>(getSearchPlacesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getSearchPlacesQueryKey = (params?: SearchPlacesParams,) => {
    return [
    `/api/v1/geo/search`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSearchPlacesQueryOptions = <TData = Awaited<ReturnType<typeof searchPlaces>>, TError = HTTPValidationError>(params: SearchPlacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPlaces>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchPlacesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchPlaces>>> = ({ signal }) => searchPlaces(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchPlaces>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchPlacesQueryResult = NonNullable<Awaited<ReturnType<typeof searchPlaces>>>
export type SearchPlacesQueryError = HTTPValidationError


export function useSearchPlaces<TData = Awaited<ReturnType<typeof searchPlaces>>, TError = HTTPValidationError>(
 params: SearchPlacesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPlaces>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchPlaces>>,
          TError,
          Awaited<ReturnType<typeof searchPlaces>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchPlaces<TData = Awaited<ReturnType<typeof searchPlaces>>, TError = HTTPValidationError>(
 params: SearchPlacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPlaces>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchPlaces>>,
          TError,
          Awaited<ReturnType<typeof searchPlaces>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchPlaces<TData = Awaited<ReturnType<typeof searchPlaces>>, TError = HTTPValidationError>(
 params: SearchPlacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPlaces>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search Places
 */

export function useSearchPlaces<TData = Awaited<ReturnType<typeof searchPlaces>>, TError = HTTPValidationError>(
 params: SearchPlacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPlaces>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchPlacesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get Surroundings
 */
export const getGetSurroundingsUrl = (projectId: string,) => {


  

  return `/api/v1/projects/${projectId}/surroundings`
}

export const getSurroundings = async (projectId: string, options?: RequestInit): Promise<SurroundingsOut> => {
  
  return httpClient<SurroundingsOut>(getGetSurroundingsUrl(projectId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetSurroundingsQueryKey = (projectId?: string,) => {
    return [
    `/api/v1/projects/${projectId}/surroundings`
    ] as const;
    }

    
export const getGetSurroundingsQueryOptions = <TData = Awaited<ReturnType<typeof getSurroundings>>, TError = HTTPValidationError>(projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSurroundings>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSurroundingsQueryKey(projectId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSurroundings>>> = ({ signal }) => getSurroundings(projectId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(projectId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSurroundings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSurroundingsQueryResult = NonNullable<Awaited<ReturnType<typeof getSurroundings>>>
export type GetSurroundingsQueryError = HTTPValidationError


export function useGetSurroundings<TData = Awaited<ReturnType<typeof getSurroundings>>, TError = HTTPValidationError>(
 projectId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSurroundings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSurroundings>>,
          TError,
          Awaited<ReturnType<typeof getSurroundings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSurroundings<TData = Awaited<ReturnType<typeof getSurroundings>>, TError = HTTPValidationError>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSurroundings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSurroundings>>,
          TError,
          Awaited<ReturnType<typeof getSurroundings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSurroundings<TData = Awaited<ReturnType<typeof getSurroundings>>, TError = HTTPValidationError>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSurroundings>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Surroundings
 */

export function useGetSurroundings<TData = Awaited<ReturnType<typeof getSurroundings>>, TError = HTTPValidationError>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSurroundings>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSurroundingsQueryOptions(projectId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Fetch the terrain, the aerial photo and the buildings around the place (10 to 30 s). Replaces
earlier surroundings; the viewer shows them in the Final and Ultra looks, never the builder.
 * @summary Fetch Surroundings
 */
export const getFetchSurroundingsUrl = (projectId: string,) => {


  

  return `/api/v1/projects/${projectId}/surroundings`
}

export const fetchSurroundings = async (projectId: string,
    fetchIn: FetchIn, options?: RequestInit): Promise<SurroundingsOut> => {
  
  return httpClient<SurroundingsOut>(getFetchSurroundingsUrl(projectId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      fetchIn,)
  }
);}




export const getFetchSurroundingsMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fetchSurroundings>>, TError,{projectId: string;data: FetchIn}, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof fetchSurroundings>>, TError,{projectId: string;data: FetchIn}, TContext> => {

const mutationKey = ['fetchSurroundings'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof fetchSurroundings>>, {projectId: string;data: FetchIn}> = (props) => {
          const {projectId,data} = props ?? {};

          return  fetchSurroundings(projectId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type FetchSurroundingsMutationResult = NonNullable<Awaited<ReturnType<typeof fetchSurroundings>>>
    export type FetchSurroundingsMutationBody = FetchIn
    export type FetchSurroundingsMutationError = HTTPValidationError

    /**
 * @summary Fetch Surroundings
 */
export const useFetchSurroundings = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fetchSurroundings>>, TError,{projectId: string;data: FetchIn}, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof fetchSurroundings>>,
        TError,
        {projectId: string;data: FetchIn},
        TContext
      > => {

      const mutationOptions = getFetchSurroundingsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Where the scene sits in its surroundings (the alignment editor).
 * @summary Align Surroundings
 */
export const getAlignSurroundingsUrl = (projectId: string,) => {


  

  return `/api/v1/projects/${projectId}/surroundings`
}

export const alignSurroundings = async (projectId: string,
    alignmentIn: AlignmentIn, options?: RequestInit): Promise<SurroundingsOut> => {
  
  return httpClient<SurroundingsOut>(getAlignSurroundingsUrl(projectId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      alignmentIn,)
  }
);}




export const getAlignSurroundingsMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof alignSurroundings>>, TError,{projectId: string;data: AlignmentIn}, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof alignSurroundings>>, TError,{projectId: string;data: AlignmentIn}, TContext> => {

const mutationKey = ['alignSurroundings'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof alignSurroundings>>, {projectId: string;data: AlignmentIn}> = (props) => {
          const {projectId,data} = props ?? {};

          return  alignSurroundings(projectId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AlignSurroundingsMutationResult = NonNullable<Awaited<ReturnType<typeof alignSurroundings>>>
    export type AlignSurroundingsMutationBody = AlignmentIn
    export type AlignSurroundingsMutationError = HTTPValidationError

    /**
 * @summary Align Surroundings
 */
export const useAlignSurroundings = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof alignSurroundings>>, TError,{projectId: string;data: AlignmentIn}, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof alignSurroundings>>,
        TError,
        {projectId: string;data: AlignmentIn},
        TContext
      > => {

      const mutationOptions = getAlignSurroundingsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete Surroundings
 */
export const getDeleteSurroundingsUrl = (projectId: string,) => {


  

  return `/api/v1/projects/${projectId}/surroundings`
}

export const deleteSurroundings = async (projectId: string, options?: RequestInit): Promise<void> => {
  
  return httpClient<void>(getDeleteSurroundingsUrl(projectId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteSurroundingsMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSurroundings>>, TError,{projectId: string}, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteSurroundings>>, TError,{projectId: string}, TContext> => {

const mutationKey = ['deleteSurroundings'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSurroundings>>, {projectId: string}> = (props) => {
          const {projectId} = props ?? {};

          return  deleteSurroundings(projectId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteSurroundingsMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSurroundings>>>
    
    export type DeleteSurroundingsMutationError = HTTPValidationError

    /**
 * @summary Delete Surroundings
 */
export const useDeleteSurroundings = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSurroundings>>, TError,{projectId: string}, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteSurroundings>>,
        TError,
        {projectId: string},
        TContext
      > => {

      const mutationOptions = getDeleteSurroundingsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    