/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  SharedProjectOut
} from '../../model';

import { httpClient } from '../../http-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * The read-only view behind a share link (#24): the scene (current or pinned version),
its renders and photos. Nothing that could change the project, nothing the owner wrote.
 * @summary Shared Project
 */
export const getSharedProjectUrl = (token: string,) => {


  

  return `/api/v1/shared/${token}`
}

export const sharedProject = async (token: string, options?: RequestInit): Promise<SharedProjectOut> => {
  
  return httpClient<SharedProjectOut>(getSharedProjectUrl(token),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getSharedProjectQueryKey = (token?: string,) => {
    return [
    `/api/v1/shared/${token}`
    ] as const;
    }

    
export const getSharedProjectQueryOptions = <TData = Awaited<ReturnType<typeof sharedProject>>, TError = HTTPValidationError>(token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sharedProject>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSharedProjectQueryKey(token);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof sharedProject>>> = ({ signal }) => sharedProject(token, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(token), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof sharedProject>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SharedProjectQueryResult = NonNullable<Awaited<ReturnType<typeof sharedProject>>>
export type SharedProjectQueryError = HTTPValidationError


export function useSharedProject<TData = Awaited<ReturnType<typeof sharedProject>>, TError = HTTPValidationError>(
 token: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof sharedProject>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sharedProject>>,
          TError,
          Awaited<ReturnType<typeof sharedProject>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSharedProject<TData = Awaited<ReturnType<typeof sharedProject>>, TError = HTTPValidationError>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sharedProject>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sharedProject>>,
          TError,
          Awaited<ReturnType<typeof sharedProject>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSharedProject<TData = Awaited<ReturnType<typeof sharedProject>>, TError = HTTPValidationError>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sharedProject>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Shared Project
 */

export function useSharedProject<TData = Awaited<ReturnType<typeof sharedProject>>, TError = HTTPValidationError>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sharedProject>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSharedProjectQueryOptions(token,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



