/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BodyCreateProject,
  ChatMessageOut,
  HTTPValidationError,
  JobEventOut,
  JobEventsParams,
  JobOut,
  ModifyRequest,
  ProjectOut,
  ProjectSummaryOut,
  SceneFilesOut,
  SceneFilesParams
} from '../../model';

import { httpClient } from '../../http-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List Projects
 */
export const getListProjectsUrl = () => {


  

  return `/api/v1/projects`
}

export const listProjects = async ( options?: RequestInit): Promise<ProjectSummaryOut[]> => {
  
  return httpClient<ProjectSummaryOut[]>(getListProjectsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListProjectsQueryKey = () => {
    return [
    `/api/v1/projects`
    ] as const;
    }

    
export const getListProjectsQueryOptions = <TData = Awaited<ReturnType<typeof listProjects>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListProjectsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listProjects>>> = ({ signal }) => listProjects({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListProjectsQueryResult = NonNullable<Awaited<ReturnType<typeof listProjects>>>
export type ListProjectsQueryError = unknown


export function useListProjects<TData = Awaited<ReturnType<typeof listProjects>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProjects>>,
          TError,
          Awaited<ReturnType<typeof listProjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProjects<TData = Awaited<ReturnType<typeof listProjects>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProjects>>,
          TError,
          Awaited<ReturnType<typeof listProjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProjects<TData = Awaited<ReturnType<typeof listProjects>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Projects
 */

export function useListProjects<TData = Awaited<ReturnType<typeof listProjects>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListProjectsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Create Project
 */
export const getCreateProjectUrl = () => {


  

  return `/api/v1/projects`
}

export const createProject = async (bodyCreateProject: BodyCreateProject, options?: RequestInit): Promise<ProjectOut> => {
    const formData = new FormData();
formData.append(`name`, bodyCreateProject.name)
formData.append(`plan`, bodyCreateProject.plan)
bodyCreateProject.photos.forEach(value => formData.append(`photos`, value));
bodyCreateProject.sides.forEach(value => formData.append(`sides`, value));

  return httpClient<ProjectOut>(getCreateProjectUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}




export const getCreateProjectMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProject>>, TError,{data: BodyCreateProject}, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof createProject>>, TError,{data: BodyCreateProject}, TContext> => {

const mutationKey = ['createProject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProject>>, {data: BodyCreateProject}> = (props) => {
          const {data} = props ?? {};

          return  createProject(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateProjectMutationResult = NonNullable<Awaited<ReturnType<typeof createProject>>>
    export type CreateProjectMutationBody = BodyCreateProject
    export type CreateProjectMutationError = HTTPValidationError

    /**
 * @summary Create Project
 */
export const useCreateProject = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProject>>, TError,{data: BodyCreateProject}, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProject>>,
        TError,
        {data: BodyCreateProject},
        TContext
      > => {

      const mutationOptions = getCreateProjectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get Project
 */
export const getGetProjectUrl = (projectId: string,) => {


  

  return `/api/v1/projects/${projectId}`
}

export const getProject = async (projectId: string, options?: RequestInit): Promise<ProjectOut> => {
  
  return httpClient<ProjectOut>(getGetProjectUrl(projectId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetProjectQueryKey = (projectId?: string,) => {
    return [
    `/api/v1/projects/${projectId}`
    ] as const;
    }

    
export const getGetProjectQueryOptions = <TData = Awaited<ReturnType<typeof getProject>>, TError = HTTPValidationError>(projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProjectQueryKey(projectId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProject>>> = ({ signal }) => getProject(projectId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(projectId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProjectQueryResult = NonNullable<Awaited<ReturnType<typeof getProject>>>
export type GetProjectQueryError = HTTPValidationError


export function useGetProject<TData = Awaited<ReturnType<typeof getProject>>, TError = HTTPValidationError>(
 projectId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProject>>,
          TError,
          Awaited<ReturnType<typeof getProject>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProject<TData = Awaited<ReturnType<typeof getProject>>, TError = HTTPValidationError>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProject>>,
          TError,
          Awaited<ReturnType<typeof getProject>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProject<TData = Awaited<ReturnType<typeof getProject>>, TError = HTTPValidationError>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Project
 */

export function useGetProject<TData = Awaited<ReturnType<typeof getProject>>, TError = HTTPValidationError>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProjectQueryOptions(projectId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Delete Project
 */
export const getDeleteProjectUrl = (projectId: string,) => {


  

  return `/api/v1/projects/${projectId}`
}

export const deleteProject = async (projectId: string, options?: RequestInit): Promise<void> => {
  
  return httpClient<void>(getDeleteProjectUrl(projectId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteProjectMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProject>>, TError,{projectId: string}, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProject>>, TError,{projectId: string}, TContext> => {

const mutationKey = ['deleteProject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProject>>, {projectId: string}> = (props) => {
          const {projectId} = props ?? {};

          return  deleteProject(projectId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteProjectMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProject>>>
    
    export type DeleteProjectMutationError = HTTPValidationError

    /**
 * @summary Delete Project
 */
export const useDeleteProject = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProject>>, TError,{projectId: string}, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProject>>,
        TError,
        {projectId: string},
        TContext
      > => {

      const mutationOptions = getDeleteProjectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Generate
 */
export const getGenerateUrl = (projectId: string,) => {


  

  return `/api/v1/projects/${projectId}/generate`
}

export const generate = async (projectId: string, options?: RequestInit): Promise<JobOut> => {
  
  return httpClient<JobOut>(getGenerateUrl(projectId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getGenerateMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generate>>, TError,{projectId: string}, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof generate>>, TError,{projectId: string}, TContext> => {

const mutationKey = ['generate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof generate>>, {projectId: string}> = (props) => {
          const {projectId} = props ?? {};

          return  generate(projectId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GenerateMutationResult = NonNullable<Awaited<ReturnType<typeof generate>>>
    
    export type GenerateMutationError = HTTPValidationError

    /**
 * @summary Generate
 */
export const useGenerate = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generate>>, TError,{projectId: string}, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof generate>>,
        TError,
        {projectId: string},
        TContext
      > => {

      const mutationOptions = getGenerateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Modify
 */
export const getModifyUrl = (projectId: string,) => {


  

  return `/api/v1/projects/${projectId}/modify`
}

export const modify = async (projectId: string,
    modifyRequest: ModifyRequest, options?: RequestInit): Promise<JobOut> => {
  
  return httpClient<JobOut>(getModifyUrl(projectId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      modifyRequest,)
  }
);}




export const getModifyMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof modify>>, TError,{projectId: string;data: ModifyRequest}, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof modify>>, TError,{projectId: string;data: ModifyRequest}, TContext> => {

const mutationKey = ['modify'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof modify>>, {projectId: string;data: ModifyRequest}> = (props) => {
          const {projectId,data} = props ?? {};

          return  modify(projectId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ModifyMutationResult = NonNullable<Awaited<ReturnType<typeof modify>>>
    export type ModifyMutationBody = ModifyRequest
    export type ModifyMutationError = HTTPValidationError

    /**
 * @summary Modify
 */
export const useModify = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof modify>>, TError,{projectId: string;data: ModifyRequest}, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof modify>>,
        TError,
        {projectId: string;data: ModifyRequest},
        TContext
      > => {

      const mutationOptions = getModifyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List Jobs
 */
export const getListJobsUrl = (projectId: string,) => {


  

  return `/api/v1/projects/${projectId}/jobs`
}

export const listJobs = async (projectId: string, options?: RequestInit): Promise<JobOut[]> => {
  
  return httpClient<JobOut[]>(getListJobsUrl(projectId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListJobsQueryKey = (projectId?: string,) => {
    return [
    `/api/v1/projects/${projectId}/jobs`
    ] as const;
    }

    
export const getListJobsQueryOptions = <TData = Awaited<ReturnType<typeof listJobs>>, TError = HTTPValidationError>(projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listJobs>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListJobsQueryKey(projectId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listJobs>>> = ({ signal }) => listJobs(projectId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(projectId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listJobs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListJobsQueryResult = NonNullable<Awaited<ReturnType<typeof listJobs>>>
export type ListJobsQueryError = HTTPValidationError


export function useListJobs<TData = Awaited<ReturnType<typeof listJobs>>, TError = HTTPValidationError>(
 projectId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listJobs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listJobs>>,
          TError,
          Awaited<ReturnType<typeof listJobs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListJobs<TData = Awaited<ReturnType<typeof listJobs>>, TError = HTTPValidationError>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listJobs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listJobs>>,
          TError,
          Awaited<ReturnType<typeof listJobs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListJobs<TData = Awaited<ReturnType<typeof listJobs>>, TError = HTTPValidationError>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listJobs>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Jobs
 */

export function useListJobs<TData = Awaited<ReturnType<typeof listJobs>>, TError = HTTPValidationError>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listJobs>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListJobsQueryOptions(projectId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get Job
 */
export const getGetJobUrl = (projectId: string,
    jobId: string,) => {


  

  return `/api/v1/projects/${projectId}/jobs/${jobId}`
}

export const getJob = async (projectId: string,
    jobId: string, options?: RequestInit): Promise<JobOut> => {
  
  return httpClient<JobOut>(getGetJobUrl(projectId,jobId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetJobQueryKey = (projectId?: string,
    jobId?: string,) => {
    return [
    `/api/v1/projects/${projectId}/jobs/${jobId}`
    ] as const;
    }

    
export const getGetJobQueryOptions = <TData = Awaited<ReturnType<typeof getJob>>, TError = HTTPValidationError>(projectId: string,
    jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJob>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetJobQueryKey(projectId,jobId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getJob>>> = ({ signal }) => getJob(projectId,jobId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(projectId && jobId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getJob>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetJobQueryResult = NonNullable<Awaited<ReturnType<typeof getJob>>>
export type GetJobQueryError = HTTPValidationError


export function useGetJob<TData = Awaited<ReturnType<typeof getJob>>, TError = HTTPValidationError>(
 projectId: string,
    jobId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJob>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJob>>,
          TError,
          Awaited<ReturnType<typeof getJob>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetJob<TData = Awaited<ReturnType<typeof getJob>>, TError = HTTPValidationError>(
 projectId: string,
    jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJob>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJob>>,
          TError,
          Awaited<ReturnType<typeof getJob>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetJob<TData = Awaited<ReturnType<typeof getJob>>, TError = HTTPValidationError>(
 projectId: string,
    jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJob>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Job
 */

export function useGetJob<TData = Awaited<ReturnType<typeof getJob>>, TError = HTTPValidationError>(
 projectId: string,
    jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJob>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetJobQueryOptions(projectId,jobId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Job Events
 */
export const getJobEventsUrl = (projectId: string,
    jobId: string,
    params?: JobEventsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/projects/${projectId}/jobs/${jobId}/events?${stringifiedParams}` : `/api/v1/projects/${projectId}/jobs/${jobId}/events`
}

export const jobEvents = async (projectId: string,
    jobId: string,
    params?: JobEventsParams, options?: RequestInit): Promise<JobEventOut[]> => {
  
  return httpClient<JobEventOut[]>(getJobEventsUrl(projectId,jobId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getJobEventsQueryKey = (projectId?: string,
    jobId?: string,
    params?: JobEventsParams,) => {
    return [
    `/api/v1/projects/${projectId}/jobs/${jobId}/events`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getJobEventsQueryOptions = <TData = Awaited<ReturnType<typeof jobEvents>>, TError = HTTPValidationError>(projectId: string,
    jobId: string,
    params?: JobEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jobEvents>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getJobEventsQueryKey(projectId,jobId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof jobEvents>>> = ({ signal }) => jobEvents(projectId,jobId,params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(projectId && jobId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof jobEvents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type JobEventsQueryResult = NonNullable<Awaited<ReturnType<typeof jobEvents>>>
export type JobEventsQueryError = HTTPValidationError


export function useJobEvents<TData = Awaited<ReturnType<typeof jobEvents>>, TError = HTTPValidationError>(
 projectId: string,
    jobId: string,
    params: undefined |  JobEventsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof jobEvents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof jobEvents>>,
          TError,
          Awaited<ReturnType<typeof jobEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useJobEvents<TData = Awaited<ReturnType<typeof jobEvents>>, TError = HTTPValidationError>(
 projectId: string,
    jobId: string,
    params?: JobEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jobEvents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof jobEvents>>,
          TError,
          Awaited<ReturnType<typeof jobEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useJobEvents<TData = Awaited<ReturnType<typeof jobEvents>>, TError = HTTPValidationError>(
 projectId: string,
    jobId: string,
    params?: JobEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jobEvents>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Job Events
 */

export function useJobEvents<TData = Awaited<ReturnType<typeof jobEvents>>, TError = HTTPValidationError>(
 projectId: string,
    jobId: string,
    params?: JobEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jobEvents>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getJobEventsQueryOptions(projectId,jobId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Chat History
 */
export const getChatHistoryUrl = (projectId: string,) => {


  

  return `/api/v1/projects/${projectId}/chat`
}

export const chatHistory = async (projectId: string, options?: RequestInit): Promise<ChatMessageOut[]> => {
  
  return httpClient<ChatMessageOut[]>(getChatHistoryUrl(projectId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getChatHistoryQueryKey = (projectId?: string,) => {
    return [
    `/api/v1/projects/${projectId}/chat`
    ] as const;
    }

    
export const getChatHistoryQueryOptions = <TData = Awaited<ReturnType<typeof chatHistory>>, TError = HTTPValidationError>(projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof chatHistory>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getChatHistoryQueryKey(projectId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof chatHistory>>> = ({ signal }) => chatHistory(projectId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(projectId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof chatHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ChatHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof chatHistory>>>
export type ChatHistoryQueryError = HTTPValidationError


export function useChatHistory<TData = Awaited<ReturnType<typeof chatHistory>>, TError = HTTPValidationError>(
 projectId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof chatHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatHistory>>,
          TError,
          Awaited<ReturnType<typeof chatHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useChatHistory<TData = Awaited<ReturnType<typeof chatHistory>>, TError = HTTPValidationError>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof chatHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatHistory>>,
          TError,
          Awaited<ReturnType<typeof chatHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useChatHistory<TData = Awaited<ReturnType<typeof chatHistory>>, TError = HTTPValidationError>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof chatHistory>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Chat History
 */

export function useChatHistory<TData = Awaited<ReturnType<typeof chatHistory>>, TError = HTTPValidationError>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof chatHistory>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getChatHistoryQueryOptions(projectId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Restore Version
 */
export const getRestoreVersionUrl = (projectId: string,
    number: number,) => {


  

  return `/api/v1/projects/${projectId}/versions/${number}/restore`
}

export const restoreVersion = async (projectId: string,
    number: number, options?: RequestInit): Promise<ProjectOut> => {
  
  return httpClient<ProjectOut>(getRestoreVersionUrl(projectId,number),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getRestoreVersionMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof restoreVersion>>, TError,{projectId: string;number: number}, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof restoreVersion>>, TError,{projectId: string;number: number}, TContext> => {

const mutationKey = ['restoreVersion'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof restoreVersion>>, {projectId: string;number: number}> = (props) => {
          const {projectId,number} = props ?? {};

          return  restoreVersion(projectId,number,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RestoreVersionMutationResult = NonNullable<Awaited<ReturnType<typeof restoreVersion>>>
    
    export type RestoreVersionMutationError = HTTPValidationError

    /**
 * @summary Restore Version
 */
export const useRestoreVersion = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof restoreVersion>>, TError,{projectId: string;number: number}, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof restoreVersion>>,
        TError,
        {projectId: string;number: number},
        TContext
      > => {

      const mutationOptions = getRestoreVersionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Scene Files
 */
export const getSceneFilesUrl = (projectId: string,
    params?: SceneFilesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/projects/${projectId}/files?${stringifiedParams}` : `/api/v1/projects/${projectId}/files`
}

export const sceneFiles = async (projectId: string,
    params?: SceneFilesParams, options?: RequestInit): Promise<SceneFilesOut> => {
  
  return httpClient<SceneFilesOut>(getSceneFilesUrl(projectId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getSceneFilesQueryKey = (projectId?: string,
    params?: SceneFilesParams,) => {
    return [
    `/api/v1/projects/${projectId}/files`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSceneFilesQueryOptions = <TData = Awaited<ReturnType<typeof sceneFiles>>, TError = HTTPValidationError>(projectId: string,
    params?: SceneFilesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sceneFiles>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSceneFilesQueryKey(projectId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof sceneFiles>>> = ({ signal }) => sceneFiles(projectId,params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(projectId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof sceneFiles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SceneFilesQueryResult = NonNullable<Awaited<ReturnType<typeof sceneFiles>>>
export type SceneFilesQueryError = HTTPValidationError


export function useSceneFiles<TData = Awaited<ReturnType<typeof sceneFiles>>, TError = HTTPValidationError>(
 projectId: string,
    params: undefined |  SceneFilesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof sceneFiles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sceneFiles>>,
          TError,
          Awaited<ReturnType<typeof sceneFiles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSceneFiles<TData = Awaited<ReturnType<typeof sceneFiles>>, TError = HTTPValidationError>(
 projectId: string,
    params?: SceneFilesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sceneFiles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sceneFiles>>,
          TError,
          Awaited<ReturnType<typeof sceneFiles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSceneFiles<TData = Awaited<ReturnType<typeof sceneFiles>>, TError = HTTPValidationError>(
 projectId: string,
    params?: SceneFilesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sceneFiles>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Scene Files
 */

export function useSceneFiles<TData = Awaited<ReturnType<typeof sceneFiles>>, TError = HTTPValidationError>(
 projectId: string,
    params?: SceneFilesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sceneFiles>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSceneFilesQueryOptions(projectId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



