/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

export interface AlignmentIn {
  /** where the scene's origin lies, metres east of the searched point */
  x: number;
  /** … metres south of it */
  z: number;
  /**
   * degrees the scene is turned, clockwise seen from above
   * @minimum -360
   * @maximum 360
   */
  rotation: number;
  /** altitude (m) of the scene's y = 0 */
  ground: number;
}
