/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

export interface AlignmentOut {
  /** where the scene's origin lies, metres east of the searched point */
  x: number;
  /** … metres south of it */
  z: number;
  /**
   * degrees the scene is turned, clockwise seen from above
   * @minimum -360
   * @maximum 360
   */
  rotation: number;
  /** altitude (m) of the scene's y = 0 */
  ground: number;
  /**
   * metres around the house drawn in 3D (the trees, the ground by type); the aerial photo beyond (#51)
   * @minimum 30
   * @maximum 165
   */
  near?: number;
  /** false until the owner aligned the scene */
  set: boolean;
}
