/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

export interface BodyCreateProject {
  /**
   * @minLength 1
   * @maxLength 200
   */
  name: string;
  /** PDF plan set(s) */
  plans: string[];
  /** label per plan document, same order (optional) */
  plan_labels?: string[];
  /** photos of the house (optional: without any, the plans are read first) */
  photos?: string[];
  /** side per photo, same order: north|south|east|west|other */
  sides?: string[];
  /**
   * what the files cannot say: changes since the plan, materials, colours
   * @maxLength 4000
   */
  notes?: string;
}
