/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

export interface BodyAddPlanDocument {
  /** PDF plan set */
  plan: string;
  /** @maxLength 200 */
  label?: string;
}
