/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

export interface BodyCreateProject {
  /**
   * @minLength 1
   * @maxLength 200
   */
  name: string;
  /** PDF plan set */
  plan: string;
  /** façade photos */
  photos: string[];
  /** side per photo, same order: north|south|east|west|other */
  sides: string[];
}
