/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

export interface BodyInterior {
  /**
   * what to furnish and how (optional): which floor or flat, a style, a use per room
   * @maxLength 4000
   */
  message?: string;
}
