/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

/**
 * also apply the stored review findings of this version (the current one) in the same request, before the message
 */
export type BodyModifyApplyReviewOf = number | null;
