/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { ChatMessageOutJobId } from './chatMessageOutJobId';
import type { ChatMessageOutVersionNumber } from './chatMessageOutVersionNumber';

export interface ChatMessageOut {
  id: string;
  role: string;
  content: string;
  job_id: ChatMessageOutJobId;
  version_number: ChatMessageOutVersionNumber;
  attachments?: string[];
  created_at: string;
}
