/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { CritiqueIssue } from './critiqueIssue';

export interface Critique {
  /**
   * @minimum 0
   * @maximum 100
   */
  overall_score: number;
  summary: string;
  done: boolean;
  issues: CritiqueIssue[];
}
