/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

export type CritiqueIssueSeverity = typeof CritiqueIssueSeverity[keyof typeof CritiqueIssueSeverity];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CritiqueIssueSeverity = {
  major: 'major',
  minor: 'minor',
} as const;
