/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { EstimateKind } from './estimateKind';
import type { EstimateCostUsd } from './estimateCostUsd';
import type { EstimateBasis } from './estimateBasis';

export interface Estimate {
  kind: EstimateKind;
  minutes: number;
  cost_usd: EstimateCostUsd;
  basis: EstimateBasis;
  samples: number;
  model: string;
}
