/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

export type EstimateBasis = typeof EstimateBasis[keyof typeof EstimateBasis];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EstimateBasis = {
  history: 'history',
  default: 'default',
} as const;
