/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { PlaceOut } from './placeOut';
import type { FetchInRadius } from './fetchInRadius';

export interface FetchIn {
  place: PlaceOut;
  radius?: FetchInRadius;
}
