/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

export type FetchInRadius = typeof FetchInRadius[keyof typeof FetchInRadius];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FetchInRadius = {
  NUMBER_100: 100,
  NUMBER_200: 200,
  NUMBER_300: 300,
} as const;
