/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { IntakeAnswer } from './intakeAnswer';

/**
 * Optional: the owner's answers to the intake's questions (and anything else to say),
appended to the project's brief before the build starts.
 */
export interface GenerateRequest {
  /** @maxItems 12 */
  answers?: IntakeAnswer[];
  /** @maxLength 4000 */
  notes?: string;
}
