/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

export interface IntakeQuestion {
  question: string;
  /** one line: what in the model depends on the answer */
  why: string;
  /** your best-guess answer, usable as is */
  suggested: string;
}
