/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { SheetInfo } from './sheetInfo';
import type { IntakeQuestion } from './intakeQuestion';

/**
 * The intake's reading of the plan set, with the job that produced it.
 */
export interface IntakeOut {
  /** the house as drawn: footprint, storeys, roof, façades, site */
  summary: string;
  sheets: SheetInfo[];
  /** @maxItems 6 */
  questions?: IntakeQuestion[];
  job_id: string;
}
