/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

export interface IntakeAnswer {
  /**
   * @minLength 1
   * @maxLength 1000
   */
  question: string;
  /** @maxLength 2000 */
  answer: string;
}
