/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { JobEventOutPayload } from './jobEventOutPayload';

export interface JobEventOut {
  seq: number;
  type: string;
  payload: JobEventOutPayload;
  created_at: string;
}
