/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { JobOutError } from './jobOutError';
import type { JobOutResultVersion } from './jobOutResultVersion';
import type { JobOutMetrics } from './jobOutMetrics';
import type { JobOutSettings } from './jobOutSettings';
import type { JobOutFinishedAt } from './jobOutFinishedAt';

export interface JobOut {
  id: string;
  project_id: string;
  kind: string;
  status: string;
  request_text: string;
  error: JobOutError;
  result_version: JobOutResultVersion;
  metrics?: JobOutMetrics;
  settings?: JobOutSettings;
  created_at: string;
  finished_at: JobOutFinishedAt;
}
