/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

export interface KitInfo {
  name: string;
  date: string;
  note: string;
  pinned: boolean;
  dev?: boolean;
}
