/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { KitInfo } from './kitInfo';

export interface KitsOut {
  kits: KitInfo[];
  pinned: string;
  latest: string;
}
