/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { ModelInfo } from './modelInfo';
import type { ModelsOutError } from './modelsOutError';

export interface ModelsOut {
  provider: string;
  models: ModelInfo[];
  error?: ModelsOutError;
}
