/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { ModelInfoDisplayName } from './modelInfoDisplayName';
import type { ModelInfoCreatedAt } from './modelInfoCreatedAt';

/**
 * One model a provider offers (for the settings sheet's model list).
 */
export interface ModelInfo {
  id: string;
  display_name?: ModelInfoDisplayName;
  created_at?: ModelInfoCreatedAt;
}
