/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

export interface ModifyRequest {
  /**
   * @minLength 1
   * @maxLength 4000
   */
  message: string;
}
