/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { PhaseSummaryCostUsd } from './phaseSummaryCostUsd';

export interface PhaseSummary {
  turns?: number;
  llm_ms?: number;
  thinking_ms?: number;
  writing_ms?: number;
  tools_ms?: number;
  render_ms?: number;
  renders?: number;
  input_tokens?: number;
  cached_tokens?: number;
  output_tokens?: number;
  reasoning_tokens?: number;
  cache_miss_turns?: number;
  cost_usd?: PhaseSummaryCostUsd;
}
