/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { PhotoOutSide } from './photoOutSide';

export interface PhotoOut {
  id: string;
  side: PhotoOutSide;
  original_name: string;
  url: string;
}
