/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

export type PhotoOutSide = typeof PhotoOutSide[keyof typeof PhotoOutSide];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PhotoOutSide = {
  north: 'north',
  south: 'south',
  east: 'east',
  west: 'west',
  other: 'other',
} as const;
