/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

export interface PlaceOut {
  label: string;
  /** "parcel", "address", or a commune / postcode */
  kind: string;
  /** LV95 easting (EPSG:2056) */
  e: number;
  /** LV95 northing */
  n: number;
}
