/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

/**
 * One plan set of the project (#10) with its rasterised sheets.
 */
export interface PlanDocumentOut {
  id: string;
  number: number;
  label: string;
  original_name: string;
  pages: number;
  page_urls: string[];
  created_at: string;
}
