/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

/**
 * CHF per weighted m², by flat (App. 1…)
 */
export type PricesSaleM2 = {[key: string]: number | null};
