/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

/**
 * CHF/m³ of SIA 416 volume, by building key (b0, b1…)
 */
export type PricesBuildingM3 = {[key: string]: number | null};
