/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { PricesBuildingM3 } from './pricesBuildingM3';
import type { PricesLandM2 } from './pricesLandM2';
import type { PricesExcavationM3 } from './pricesExcavationM3';
import type { PricesPoolEach } from './pricesPoolEach';
import type { PricesPavingM2 } from './pricesPavingM2';
import type { PricesHedgeM } from './pricesHedgeM';
import type { PricesFenceM } from './pricesFenceM';
import type { PricesTreeEach } from './pricesTreeEach';
import type { PricesSecondaryPct } from './pricesSecondaryPct';
import type { PricesSaleM2 } from './pricesSaleM2';

/**
 * Unit prices of the estimate (page 8), CHF; null until entered.
 */
export interface Prices {
  /** CHF/m³ of SIA 416 volume, by building key (b0, b1…) */
  building_m3?: PricesBuildingM3;
  land_m2?: PricesLandM2;
  excavation_m3?: PricesExcavationM3;
  pool_each?: PricesPoolEach;
  paving_m2?: PricesPavingM2;
  hedge_m?: PricesHedgeM;
  fence_m?: PricesFenceM;
  tree_each?: PricesTreeEach;
  /** CFC 5, % of CFC 2 */
  secondary_pct?: PricesSecondaryPct;
  /** CHF per weighted m², by flat (App. 1…) */
  sale_m2?: PricesSaleM2;
}
