/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { IntakeOut } from './intakeOut';

export type ProjectOutIntake = IntakeOut | null;
