/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { PlanDocumentOut } from './planDocumentOut';
import type { ProjectOutBrief } from './projectOutBrief';
import type { ProjectOutIntake } from './projectOutIntake';
import type { RunSettings } from './runSettings';
import type { ResolvedRunSettings } from './resolvedRunSettings';
import type { PhotoOut } from './photoOut';
import type { SceneVersionOut } from './sceneVersionOut';

export interface ProjectOut {
  id: string;
  name: string;
  status: string;
  created_at: string;
  plans: PlanDocumentOut[];
  plan_pages: number;
  current_version: number;
  brief: ProjectOutBrief;
  intake: ProjectOutIntake;
  settings: RunSettings;
  effective_settings: ResolvedRunSettings;
  photos: PhotoOut[];
  versions: SceneVersionOut[];
  scene_url: string;
  plan_page_urls: string[];
}
