/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

/**
 * altitude of the ground floor's ±0.00 (m)
 */
export type ReportSettingsDatum = number | null;
