/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

/**
 * from the surroundings' parcel or the plans' title block
 */
export type ReportDefaultsParcel = string | null;
