/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

/**
 * terrace index (as the scene lists them) → its flat
 */
export type ReportSettingsTerraces = {[key: string]: string};
