/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

/**
 * flat → private garden (m²)
 */
export type ReportSettingsGardens = {[key: string]: number};
