/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

/**
 * by building key (b0: Villa…)
 */
export type ReportSettingsBuildingNames = {[key: string]: string};
