/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { ReportDefaultsParcel } from './reportDefaultsParcel';
import type { ReportDefaultsNorth } from './reportDefaultsNorth';
import type { ReportDefaultsDatum } from './reportDefaultsDatum';

/**
 * What the report fills in when the owner has not: from the plans and the surroundings.
 */
export interface ReportDefaults {
  /** from the surroundings' parcel or the plans' title block */
  parcel?: ReportDefaultsParcel;
  /** degrees the scene is turned clockwise (seen from above), when aligned */
  north?: ReportDefaultsNorth;
  /** altitude of the scene's y = 0, when aligned */
  datum?: ReportDefaultsDatum;
}
