/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

/**
 * the slab under the lowest storey (m), when the model has none
 */
export type ReportSettingsSlabThickness = number | null;
