/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

/**
 * e.g. villa de deux appartements
 */
export type ReportSettingsDescription = string | null;
