/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

/**
 * altitude of the scene's y = 0, when aligned
 */
export type ReportDefaultsDatum = number | null;
