/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

/**
 * degrees the scene is turned clockwise (seen from above), when aligned
 */
export type ReportDefaultsNorth = number | null;
