/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { ReportSettingsDescription } from './reportSettingsDescription';
import type { ReportSettingsParcel } from './reportSettingsParcel';
import type { ReportSettingsBuildingNames } from './reportSettingsBuildingNames';
import type { ReportSettingsSlabThickness } from './reportSettingsSlabThickness';
import type { ReportSettingsDatum } from './reportSettingsDatum';
import type { ReportSettingsPlotArea } from './reportSettingsPlotArea';
import type { Weights } from './weights';
import type { Prices } from './prices';
import type { ReportSettingsTerraces } from './reportSettingsTerraces';
import type { ReportSettingsGardens } from './reportSettingsGardens';

/**
 * The report's settings, saved on the project.
 */
export interface ReportSettings {
  /** e.g. villa de deux appartements */
  description?: ReportSettingsDescription;
  /** e.g. BF n° 3013, Le Mont-sur-Lausanne */
  parcel?: ReportSettingsParcel;
  /** by building key (b0: Villa…) */
  building_names?: ReportSettingsBuildingNames;
  /** the slab under the lowest storey (m), when the model has none */
  slab_thickness?: ReportSettingsSlabThickness;
  /** altitude of the ground floor's ±0.00 (m) */
  datum?: ReportSettingsDatum;
  /** m², when the model has no plot */
  plot_area?: ReportSettingsPlotArea;
  weights?: Weights;
  prices?: Prices;
  /** terrace index (as the scene lists them) → its flat */
  terraces?: ReportSettingsTerraces;
  /** flat → private garden (m²) */
  gardens?: ReportSettingsGardens;
}
