/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

/**
 * m², when the model has no plot
 */
export type ReportSettingsPlotArea = number | null;
