/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

export type ResolvedRunSettingsBuilderEffort = typeof ResolvedRunSettingsBuilderEffort[keyof typeof ResolvedRunSettingsBuilderEffort];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResolvedRunSettingsBuilderEffort = {
  none: 'none',
  minimal: 'minimal',
  low: 'low',
  medium: 'medium',
  high: 'high',
  xhigh: 'xhigh',
  max: 'max',
} as const;
