/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

export type ResolvedRunSettingsPreset = typeof ResolvedRunSettingsPreset[keyof typeof ResolvedRunSettingsPreset];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResolvedRunSettingsPreset = {
  quick: 'quick',
  full: 'full',
  custom: 'custom',
} as const;
