/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

export type ResolvedRunSettingsRenderQuality = typeof ResolvedRunSettingsRenderQuality[keyof typeof ResolvedRunSettingsRenderQuality];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResolvedRunSettingsRenderQuality = {
  low: 'low',
  medium: 'medium',
  high: 'high',
} as const;
