/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

export type ResolvedRunSettingsProvider = typeof ResolvedRunSettingsProvider[keyof typeof ResolvedRunSettingsProvider];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResolvedRunSettingsProvider = {
  anthropic: 'anthropic',
  openai: 'openai',
} as const;
