/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { ResolvedRunSettingsProvider } from './resolvedRunSettingsProvider';
import type { ResolvedRunSettingsBuilderEffort } from './resolvedRunSettingsBuilderEffort';
import type { ResolvedRunSettingsCriticEffort } from './resolvedRunSettingsCriticEffort';
import type { ResolvedRunSettingsRenderQuality } from './resolvedRunSettingsRenderQuality';
import type { ResolvedRunSettingsPreset } from './resolvedRunSettingsPreset';

/**
 * The complete settings a job runs with.
 */
export interface ResolvedRunSettings {
  provider: ResolvedRunSettingsProvider;
  model: string;
  critic_model: string;
  builder_effort: ResolvedRunSettingsBuilderEffort;
  critic_effort: ResolvedRunSettingsCriticEffort;
  critic_rounds: number;
  max_steps: number;
  render_quality: ResolvedRunSettingsRenderQuality;
  max_tokens: number;
  preset?: ResolvedRunSettingsPreset;
  notes?: string[];
}
