/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

export type RunEstimateKind = typeof RunEstimateKind[keyof typeof RunEstimateKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RunEstimateKind = {
  intake: 'intake',
  generate: 'generate',
  modify: 'modify',
} as const;
