/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { PhaseSummary } from './phaseSummary';
import type { RunSummaryCostUsd } from './runSummaryCostUsd';

/**
 * Totals of a job, by phase and by activity.
 */
export interface RunSummary {
  wall_ms?: number;
  turns?: number;
  builder?: PhaseSummary;
  critic?: PhaseSummary;
  edits?: number;
  edits_per_turn_avg?: number;
  edits_per_turn_max?: number;
  single_edit_turns?: number;
  cost_usd?: RunSummaryCostUsd;
  models?: string[];
}
