/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { RunSettingsProvider } from './runSettingsProvider';
import type { RunSettingsModel } from './runSettingsModel';
import type { RunSettingsBuilderEffort } from './runSettingsBuilderEffort';
import type { RunSettingsCriticEffort } from './runSettingsCriticEffort';
import type { RunSettingsCriticRounds } from './runSettingsCriticRounds';
import type { RunSettingsMaxSteps } from './runSettingsMaxSteps';
import type { RunSettingsRenderQuality } from './runSettingsRenderQuality';

/**
 * What the owner sets on a project; unset fields fall back to the `.env` defaults.
 */
export interface RunSettings {
  provider?: RunSettingsProvider;
  model?: RunSettingsModel;
  builder_effort?: RunSettingsBuilderEffort;
  critic_effort?: RunSettingsCriticEffort;
  critic_rounds?: RunSettingsCriticRounds;
  max_steps?: RunSettingsMaxSteps;
  render_quality?: RunSettingsRenderQuality;
}
