/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { SceneVersionOutCriticScore } from './sceneVersionOutCriticScore';
import type { SceneVersionOutRenderUrls } from './sceneVersionOutRenderUrls';

export interface SceneVersionOut {
  id: string;
  number: number;
  kind: string;
  label: string;
  summary: string;
  critic_score: SceneVersionOutCriticScore;
  created_at: string;
  scene_url: string;
  render_urls: SceneVersionOutRenderUrls;
}
