/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

export type SearchPlacesParams = {
/**
 * @minLength 2
 * @maxLength 200
 */
q: string;
};
