/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { ShareRequest } from './shareRequest';

export type ShareProjectBody = ShareRequest | null;
