/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { ShareOutVersion } from './shareOutVersion';

export interface ShareOut {
  token: string;
  url: string;
  version: ShareOutVersion;
}
