/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { SharedProjectOutRenderUrls } from './sharedProjectOutRenderUrls';

/**
 * What a recipient of a share link gets: the scene and its pictures, nothing else
(no jobs, chat, brief, intake, code, settings).
 */
export interface SharedProjectOut {
  name: string;
  version: number;
  pinned: boolean;
  scene_url: string;
  render_urls: SharedProjectOutRenderUrls;
  photo_urls: string[];
  created_at: string;
}
