/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

export type SheetInfoKind = typeof SheetInfoKind[keyof typeof SheetInfoKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SheetInfoKind = {
  floor_plan: 'floor_plan',
  elevation: 'elevation',
  section: 'section',
  site_plan: 'site_plan',
  roof_plan: 'roof_plan',
  detail: 'detail',
  other: 'other',
} as const;
