/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { SheetInfoKind } from './sheetInfoKind';
import type { SheetInfoElevationsItem } from './sheetInfoElevationsItem';

export interface SheetInfo {
  /**
   * 1-based sheet number, in upload order
   * @minimum 1
   */
  page: number;
  kind: SheetInfoKind;
  /** short, e.g. 'ground floor plan 1:100', 'south elevation' */
  label: string;
  /** for elevation sheets: the façades drawn on it (by compass side) */
  elevations?: SheetInfoElevationsItem[];
}
