/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

export type SheetInfoElevationsItem = typeof SheetInfoElevationsItem[keyof typeof SheetInfoElevationsItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SheetInfoElevationsItem = {
  north: 'north',
  south: 'south',
  east: 'east',
  west: 'west',
} as const;
