/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { PlaceOut } from './placeOut';

export type SurroundingsOutPlace = PlaceOut | null;
