/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

/**
 * what the plans' title block names (parcel and commune)
 */
export type SurroundingsOutSuggestion = string | null;
