/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

/**
 * the folder the scene page loads them from (?context=)
 */
export type SurroundingsOutUrl = string | null;
