/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */
import type { SurroundingsOutSuggestion } from './surroundingsOutSuggestion';
import type { SurroundingsOutPlace } from './surroundingsOutPlace';
import type { SurroundingsOutRadius } from './surroundingsOutRadius';
import type { SurroundingsOutUrl } from './surroundingsOutUrl';
import type { SurroundingsOutPhotoUrl } from './surroundingsOutPhotoUrl';
import type { SurroundingsOutBuildings } from './surroundingsOutBuildings';
import type { SurroundingsOutAlignment } from './surroundingsOutAlignment';
import type { SurroundingsOutFetchedAt } from './surroundingsOutFetchedAt';

export interface SurroundingsOut {
  exists: boolean;
  /** what the plans' title block names (parcel and commune) */
  suggestion?: SurroundingsOutSuggestion;
  place?: SurroundingsOutPlace;
  radius?: SurroundingsOutRadius;
  /** the folder the scene page loads them from (?context=) */
  url?: SurroundingsOutUrl;
  photo_url?: SurroundingsOutPhotoUrl;
  buildings?: SurroundingsOutBuildings;
  alignment?: SurroundingsOutAlignment;
  credits?: string[];
  fetched_at?: SurroundingsOutFetchedAt;
}
