/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * housegen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Shares of the weighted living area (page 9): practice, not a norm.
 */
export interface Weights {
  /**
   * @minimum 0
   * @maximum 1
   */
  balcony?: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  terrace?: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  garden?: number;
}
